### ISSUE TITLE
google chrome devtools colorscheme for vim

### ISSUE THREAD

**Issue by vzytoi** [sampixel/mood-colors#1]
hey, i really likes your work and I wanted to know if you ever think of making a google chrome dev tools color scheme copy for vim. have a good day.
![azdazdazdazdazdazd](https://user-images.githubusercontent.com/65293868/122556339-ab44e900-d03b-11eb-802a-98ba3658449d.PNG)

**Comment by sampixel** [comment]
Hi! Are you talking about the light theme used in the inspector browser or
what?
Anyway, i believe i can do it but this repo needs many fixes so it can take
some time :)

**Comment by vzytoi** [comment]
Thank you for the answer, I'm talking about the dark one. 
I took some screenshots to help you visualize

- **JavaScript** : https://i.imgur.com/Zt6tG9J.png
- **HTML** : https://i.imgur.com/JZ32FbR.png
- **CSS** : https://i.imgur.com/YgtfZYG.png

Have a good day!

**Comment by sampixel** [comment]
Thank you too for telling me that is the dark one!
I'll consider it since i've actually some other stuff to accomplish right
now and thank you for giving me feedbacks.
